name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository_owner }}/ci-cd-kv-sample:latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Terraform Init
        run: terraform init

      - name: Run Terraform Validate
        run: terraform validate